### PR TITLE
Cache the response content-type header

### PR DESCRIPTION
**Pull request by GordonLesti**

### CODE REVIEW

**Comment by GordonLesti** [comment]
Hello @kurtinge 
please review as this is build on your [Cache the response content-type header](https://github.com/GordonLesti/Lesti_Fpc/pull/184).

**Comment by kurtinge** [comment]
Hi @GordonLesti 

I think what you did here is a great solution.
I really like the idea of the cacheitem object. That makes it easier to extend if there is needed to add new elements to the cache.

The only "downside" I can think of right now is that the serialization of the object is about 100 bytes larger than for an array serialization, but looking at the big picture that is proably nothing to worry about.

**Comment by GordonLesti** [comment]
Yes, I guess you are right. I will improve that tomorrow.

**Comment by GordonLesti** [comment]
@kurtinge better?

**Comment by kurtinge** [comment]
I think this looks very good.

**Pull request merged**
