### PR TITLE
fixed warning 'preg_match(): Delimiter must not be alphanumeric or ba…

### PR DESCRIPTION
**Pull request by firewizard**
…ckslash'

### CODE REVIEW

**Comment by GordonLesti** [comment]
Hello @firewizard 
can you explain that PR a little bit more detailed? The default values for [miss_uri_params](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.6/app/code/community/Lesti/Fpc/etc/config.xml#L269) can not reproduce such a warning or I'm wrong?

**Comment by firewizard** [comment]
Try no_cache=1, which is something that i have in those miss params from previous versions of the plugin


-------- Original message --------From: Gordon Lesti <notifications@github.com> Date: 10/12/16  17:12  (GMT+02:00) To: GordonLesti/Lesti_Fpc <Lesti_Fpc@noreply.github.com> Cc: Cristian Nicolescu <cristi@mandagreen.com>, Mention <mention@noreply.github.com> Subject: Re: [GordonLesti/Lesti_Fpc] fixed warning 'preg_match(): Delimiter must not be alphanumeric or ba… (#259) 
Hello @firewizard 

can you explain that PR a little bit more detailed? The default values for miss_uri_params can not reproduce such a warning or I'm wrong?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GordonLesti/Lesti_Fpc","title":"GordonLesti/Lesti_Fpc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/GordonLesti/Lesti_Fpc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GordonLesti in #259: Hello @firewizard \r\ncan you explain that PR a little bit more detailed? The default values for [miss_uri_params](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.6/app/code/community/Lesti/Fpc/etc/config.xml#L269) can not reproduce such a warning or I'm wrong?"}],"action":{"name":"View Pull Request","url":"https://github.com/GordonLesti/Lesti_Fpc/pull/259#issuecomment-253224829"}}}

**Comment by GordonLesti** [comment]
Yes,
this was a bug in previous versions. I'm sorry. But your current PR would require to remove the slashes from the current [miss_uri_params](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.6/app/code/community/Lesti/Fpc/etc/config.xml#L269) and I guess it wouldn't be possible to use [Pattern Modifiers](http://php.net/manual/en/reference.pcre.pattern.modifiers.php).
_First time that I checked why [preg_match](http://php.net/manual/en/function.preg-match.php) needs slashes._

**Comment by firewizard** [comment]
ok, got it - your new version is not backward compatible ;) I'm closing the PR

**Comment by GordonLesti** [comment]
I'm sorry, but I really appreciate your input.

**Pull request closed without merging**
