### PR TITLE
Add caching for automatic layered navigation attributes parameters

### PR DESCRIPTION
**Pull request by rikwillems**

### CODE REVIEW

**Comment by rikwillems** [comment]
How can I fix this build error?

**Comment by GordonLesti** [comment]
I guess there are just three phpcs errors:
```
FILE: ...rdonLesti/Lesti_Fpc/app/code/community/Lesti/Fpc/Helper/Data.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 176 | ERROR | Line exceeds maximum limit of 120 characters; contains
     |       | 129 characters
 183 | ERROR | Line exceeds maximum limit of 120 characters; contains
     |       | 199 characters
 185 | ERROR | Expected "} else {\n"; found "}\n            else {\n"
----------------------------------------------------------------------
```
If you want to, I can fix them and merge this feature.

**Comment by rikwillems** [comment]
Ok, nice to know. Where did you find that info?
If you think my patch is good please merge.

**Comment by GordonLesti** [comment]
for example here https://travis-ci.org/GordonLesti/Lesti_Fpc/jobs/73353797

**Comment by GordonLesti** [comment]
@erikhansen @rikwillems thank you both for this nice PR. I'm very sorry that it took so long for me to merge it.

**Comment by erikhansen** [comment]
@GordonLesti Thanks for building and maintaining such a great extension. 
@rikwillems Thanks for your work on this PR.

**Comment by rikwillems** [comment]
@GordonLesti @erikhansen Cool we got it in.

**Comment by rafaelpatro** [comment]
Hi, great solution in layered navigation!
* Shoundn't we set an expiring time for the cached attributes? Does that make sense?
* Could we clean that cache when managing attributes? (ex.: eav_entity_attribute_save_after)

**Comment by GordonLesti** [comment]
@rafaelpatro good point

**Pull request merged**
